### ISSUE TITLE
Add auth screen

### ISSUE THREAD

**Issue by kauffj** [lbryio/api-forms#10]
As a first step:

1) Change the landing area to be just a request for an auth token to continue.
2) Store the provided auth token locally.
3) Remove the auth token from existing forms and use the locally stored one.
4) Block access to all forms unless a valid session exists. Redirect to the auth page if not.

There may be some considerations around tokens expiring, as well.

**Comment by maximest-pierre** [comment]
From my test and also from the code that is already there. The token is already stored locally and also they are autofill. So number 2 is already done.

**Comment by maximest-pierre** [comment]
Nope I will get to this after I finishing up the youtube page
