### ISSUE TITLE
Bring API forms into a LBRY domain / drop heroku domain

### ISSUE THREAD

**Issue by kauffj** [lbryio/api-forms#8]
I'd suggest `internal.lbry.io` or `forms.lbry.io`.

For now, fine to keep the same server - just add a record.

This will also let you learn the DNS setup if you haven't.

**Comment by kauffj** [comment]
https://lbry-api-forms.herokuapp.com/

**Comment by lyoshenka** [comment]
this already exists: https://apiforms.lbry.tech/

**Comment by kauffj** [comment]
@lyoshenka re-opening to drop the old domain and assigning to @nikooo777

**Comment by nikooo777** [comment]
i believe we can't really remove the existing one, can we? the endpoint is automatically generated with the instance and it sticks with it as far as I understand.
